SET SCHEMA PUBLIC;

DROP TABLE IF EXISTS USER_RESTAURANT_TBL;
DROP TABLE IF EXISTS SPRING_SESSION_ATTRIBUTES;
DROP TABLE IF EXISTS SPRING_SESSION;
DROP TABLE IF EXISTS RESTAURANT_TBL;

create table SPRING_SESSION
(
    PRIMARY_ID            CHARACTER(36) not null,
    SESSION_ID            CHARACTER(36) not null unique,
    CREATION_TIME         BIGINT        not null,
    LAST_ACCESS_TIME      BIGINT        not null,
    MAX_INACTIVE_INTERVAL INTEGER       not null,
    EXPIRY_TIME           BIGINT        not null,
    PRINCIPAL_NAME        CHARACTER VARYING(100),
    constraint SPRING_SESSION_PK
        primary key (PRIMARY_ID)
);

create table SPRING_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID CHARACTER(36)              not null,
    ATTRIBUTE_NAME     CHARACTER VARYING(200)     not null,
    ATTRIBUTE_BYTES    BINARY VARYING(1000000000) not null,
    constraint SPRING_SESSION_ATTRIBUTES_PK
        primary key (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    constraint SPRING_SESSION_ATTRIBUTES_FK
        foreign key (SESSION_PRIMARY_ID) references PUBLIC.SPRING_SESSION
            on delete cascade
);



create unique index PUBLIC.SPRING_SESSION_IX1
    on SPRING_SESSION (SESSION_ID);

create index PUBLIC.SPRING_SESSION_IX2
    on SPRING_SESSION (EXPIRY_TIME);

create index PUBLIC.SPRING_SESSION_IX3
    on SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE RESTAURANT_TBL (
    RESTAURANT_ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(200),
    CUISINE VARCHAR(100),
    DESCRIPTION VARCHAR(10000)
);

CREATE TABLE SESSION_RESTAURANT_TBL (
    SESSION_ID CHARACTER(36) NOT NULL,
    RESTAURANT_ID LONG NOT NULL,

    PRIMARY KEY (SESSION_ID, RESTAURANT_ID),
    FOREIGN KEY (SESSION_ID) REFERENCES SPRING_SESSION(SESSION_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT_TBL(RESTAURANT_ID)
);
